version: "3.8"

services:
  streamlit:
    build:
      context: .
    ports:
      - 8501:8501
    volumes:
    - .:/app
    command: sh -c "streamlit run app.py --server.port=8501 --server.address=0.0.0.0"
    container_name: streamlit